### ISSUE TITLE
Mixin apply for mod MBP failed causes infinite loading screen

### ISSUE THREAD

**Issue by NaiNonTH** [omoflop/MoreBlockPredicates#3]
Log: [latest.log](https://github.com/omoflop/MoreBlockPredicates/files/7906380/latest.log)

Highlighted Log:
[Line 296-297]
```
[22:19:59] [Render thread/ERROR]: Mixin apply for mod mbp failed mbp.mixins.json:ItemEntityRendererMixin -> net.minecraft.class_916: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_916::beforeRender with priority 1000 cannot inject into net/minecraft/class_916::method_3996(Lnet/minecraft/class_1542;FFLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V merged by net.diebuddies.mixins.MixinItemEntityRenderer with priority 1000 [PREINJECT Applicator Phase -> mbp.mixins.json:ItemEntityRendererMixin -> Prepare Injections ->  -> handler$bod000$beforeRender(Lnet/minecraft/class_1542;FFLnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_916::beforeRender with priority 1000 cannot inject into net/minecraft/class_916::method_3996(Lnet/minecraft/class_1542;FFLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V merged by net.diebuddies.mixins.MixinItemEntityRenderer with priority 1000 [PREINJECT Applicator Phase -> mbp.mixins.json:ItemEntityRendererMixin -> Prepare Injections ->  -> handler$bod000$beforeRender(Lnet/minecraft/class_1542;FFLnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
```
[Line 434]
```
java.util.concurrent.CompletionException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_916 failed
```
[Line 582-597]
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mbp.mixins.json:ItemEntityRendererMixin] from phase [DEFAULT] in config [mbp.mixins.json] from mod [mbp] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77) ~[libjf-unsafe-v0-2.3.0-6ed46d7c1aedac91.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5619.<clinit>(class_5619.java:79) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.entity.EntityRenderDispatcher.apply(EntityRenderDispatcher:369) ~[?:?]
	at net.minecraft.resource.SynchronousResourceReloadListener.method_29490(SynchronousResourceReloadListener:15) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 113 more
```

...And much more I guess

**Comment by omoflop** [comment]
Seems like a conflict with another mod that mixes into the same place. Closing for now, please create a new issue if this is still happening on the latest version.
